<!DOCTYPE html>
<html>
<head>
	<title>welcome</title>
<style>
		body
	{
           background-image: url(p1.jpg);
           background-size: 100%;
           background-repeat: no-repeat;


          
	}
	input 
	{
			
		outline: none;
		color: blue;


	}
	ul
	{

		margin-left:1100px;
		margin-top: 25px;
	   	font-size: 15px;
	}
	li
	{
        display: inline;
        margin-left: 15px;
        font-weight: lighter;

	}	
	a
	{
		color:black;
		font-weight:600
	}
	ul li a:hover
	{
		color:grey;
	}

	</style>
</head>
<body>
	<ul>
		<li><a href="index.php">Home</a></li>
		<li><a href="login.php">Login</a></li>
		<li><a href="#">About</a></li>
	</ul><br>


</body>
</html>